# Each parameter is overwritten when corresponding command line value is set
#
# NOC & WIRED CONFIGURATION
#
#
rnd_generator_seed: 0

# Supported topologies:
#   CUSTOM:
#     topology_args: [specify graph]
#   CIRCULANT:
#     topology_args: [nodes count, generators...]
#   MESH:
#     topology_args: [width, height]
#   TORUS:
#     topology_args: [width, height]
topology: TORUS
topology_args: [8, 8]
topology_channels: 3

# Routing algorithms:
#   TABLE_BASED
#   MESH_XY
#   TORUS_XY
# Each of the above labels should match a corresponding
# implementation in the routingAlgorithms source code directory
routing_algorithm: TORUS_XY

# Default routing table generators:
#   DIJKSTRA
#   DIJKSTRA_MULTIPATH
#   MESH_XY
#   just table
# routing_table: DIJKSTRA_MULTIPATH

# number of flits for each router buffer
buffer_depth: 40
# size of flits, in bits
flit_size: 32
# lenght in mm of router to router connection
r2r_link_length: 1.0

# Routing specific parameters
#   dyad_threshold: double
dyad_threshold: 0.6

# Selection Strategies:
#   RANDOM
#   BUFFER_LEVEL
#   NOP
#   KEEP_SPACE
# Each of the above labels should match a corresponding
# implementation in the selectionStrategies source code directory
selection_strategy: BUFFER_LEVEL

# SIMULATION PARAMETERS
#
clock_period_ps: 1000
# duration of reset signal assertion, expressed in cycles
reset_time: 1000
# overal simulation lenght, expressed in cycles
simulation_time: 100000
# collect stats after a given number of cycles
stats_warm_up_time: 0
# stop after a given amount of load has been processed
max_volume_to_be_drained: 0


# Verbosity level:
#   VERBOSE_OFF
#   VERBOSE_LOW
#   VERBOSE_MEDIUM
#   VERBOSE_HIGH
verbose_mode: VERBOSE_OFF

min_packet_size: 8
max_packet_size: 8
packet_injection_rate: 1
probability_of_retransmission: 1

# Traffic distribution:
#   TRAFFIC_RANDOM
#   TRAFFIC_TRANSPOSE1
#   TRAFFIC_TRANSPOSE2
#   TRAFFIC_HOTSPOT
#   TRAFFIC_TABLE_BASED
#   TRAFFIC_BIT_REVERSAL
#   TRAFFIC_SHUFFLE
#   TRAFFIC_BUTTERFLY
traffic_distribution: TRAFFIC_RANDOM
# when traffic table based is specified, use the following
# configuration file
# traffic_table_filename: "t.txt"
